# Generated by Django 5.2 on 2025-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_calls_remaining',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scan_limit',
            field=models.IntegerField(default=0),
        ),
    ]
